// <auto-generated />
using ElearningPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElearningPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ElearningPlatform.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ElearningPlatform.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Description = "Cours Java",
                            Title = "Java"
                        },
                        new
                        {
                            CourseId = 2,
                            Description = "Cours C#",
                            Title = "C#"
                        },
                        new
                        {
                            CourseId = 3,
                            Description = "Cours Python",
                            Title = "Python"
                        },
                        new
                        {
                            CourseId = 4,
                            Description = "HTML CSS JS",
                            Title = "Web"
                        });
                });

            modelBuilder.Entity("ElearningPlatform.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LessonId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            LessonId = 1,
                            CourseId = 1,
                            Title = "Intro Java",
                            VideoUrl = "https://www.youtube.com/embed/eIrMbAQSU34"
                        },
                        new
                        {
                            LessonId = 2,
                            CourseId = 2,
                            Title = "Intro C#",
                            VideoUrl = "https://www.youtube.com/embed/GhQdlIFylQ8"
                        },
                        new
                        {
                            LessonId = 3,
                            CourseId = 3,
                            Title = "Intro Python",
                            VideoUrl = "https://www.youtube.com/embed/_uQrJ0TkZlc"
                        },
                        new
                        {
                            LessonId = 4,
                            CourseId = 4,
                            Title = "Intro Web",
                            VideoUrl = "https://www.youtube.com/embed/UB1O30fR-EE"
                        });
                });

            modelBuilder.Entity("ElearningPlatform.Models.Progress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Percentage")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProgressId");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("ElearningPlatform.Models.QuizQuestion", b =>
                {
                    b.Property<int>("QuizQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("B")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("C")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correct")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QuizQuestionId");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            QuizQuestionId = 1,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "A",
                            CourseId = 1,
                            Question = "Q1?"
                        },
                        new
                        {
                            QuizQuestionId = 2,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "B",
                            CourseId = 1,
                            Question = "Q2?"
                        },
                        new
                        {
                            QuizQuestionId = 3,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "C",
                            CourseId = 1,
                            Question = "Q3?"
                        },
                        new
                        {
                            QuizQuestionId = 4,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "A",
                            CourseId = 1,
                            Question = "Q4?"
                        },
                        new
                        {
                            QuizQuestionId = 5,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "B",
                            CourseId = 1,
                            Question = "Q5?"
                        },
                        new
                        {
                            QuizQuestionId = 6,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "C",
                            CourseId = 1,
                            Question = "Q6?"
                        },
                        new
                        {
                            QuizQuestionId = 7,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "A",
                            CourseId = 2,
                            Question = "Q1?"
                        },
                        new
                        {
                            QuizQuestionId = 8,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "B",
                            CourseId = 2,
                            Question = "Q2?"
                        },
                        new
                        {
                            QuizQuestionId = 9,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "C",
                            CourseId = 2,
                            Question = "Q3?"
                        },
                        new
                        {
                            QuizQuestionId = 10,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "A",
                            CourseId = 2,
                            Question = "Q4?"
                        },
                        new
                        {
                            QuizQuestionId = 11,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "B",
                            CourseId = 2,
                            Question = "Q5?"
                        },
                        new
                        {
                            QuizQuestionId = 12,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "C",
                            CourseId = 2,
                            Question = "Q6?"
                        },
                        new
                        {
                            QuizQuestionId = 13,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "A",
                            CourseId = 3,
                            Question = "Q1?"
                        },
                        new
                        {
                            QuizQuestionId = 14,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "B",
                            CourseId = 3,
                            Question = "Q2?"
                        },
                        new
                        {
                            QuizQuestionId = 15,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "C",
                            CourseId = 3,
                            Question = "Q3?"
                        },
                        new
                        {
                            QuizQuestionId = 16,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "A",
                            CourseId = 3,
                            Question = "Q4?"
                        },
                        new
                        {
                            QuizQuestionId = 17,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "B",
                            CourseId = 3,
                            Question = "Q5?"
                        },
                        new
                        {
                            QuizQuestionId = 18,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "C",
                            CourseId = 3,
                            Question = "Q6?"
                        },
                        new
                        {
                            QuizQuestionId = 19,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "A",
                            CourseId = 4,
                            Question = "Q1?"
                        },
                        new
                        {
                            QuizQuestionId = 20,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "B",
                            CourseId = 4,
                            Question = "Q2?"
                        },
                        new
                        {
                            QuizQuestionId = 21,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "C",
                            CourseId = 4,
                            Question = "Q3?"
                        },
                        new
                        {
                            QuizQuestionId = 22,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "A",
                            CourseId = 4,
                            Question = "Q4?"
                        },
                        new
                        {
                            QuizQuestionId = 23,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "B",
                            CourseId = 4,
                            Question = "Q5?"
                        },
                        new
                        {
                            QuizQuestionId = 24,
                            A = "A",
                            B = "B",
                            C = "C",
                            Correct = "C",
                            CourseId = 4,
                            Question = "Q6?"
                        });
                });

            modelBuilder.Entity("ElearningPlatform.Models.QuizResult", b =>
                {
                    b.Property<int>("QuizResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuizResultId");

                    b.ToTable("QuizResults");
                });
#pragma warning restore 612, 618
        }
    }
}
